image: node:14.15.4

cache:
  paths:
    - node_modules/

stages:
  - build
  - lint
  - test
  - pages

install_dependencies:
  stage: build
  script:
    - yarn
  artifacts:
    paths:
      - node_modules/

lint:
  stage: lint
  script:
    - yarn lint:all

test:
  stage: test
  script:
    - yarn test

pages:
  stage: pages
  artifacts:
    paths:
      - public/
  script:
    - yarn build
  only:
    - master
  retry: 2